x11-terms/tilix: Initial 1.9.5
requires >=dev-lang/dmd-2.087 and >=dev-libs/gtkd-2.8.5[vte]
(see dlang overlay) to be already installed, with appropriate
pkg-config files. main features:
```
Libs: "-L-L/usr/lib/dmd/2.087/lib64/ -L-lgtkd-3 -L-lvted-3"
Cflags: "-I/usr/include/dlang/gtkd-3/"
```

FIXME --buildtype=plain build fails with those versions, with an error
```
Compiling D object tilix_test...rce_gx_tilix_prefeditor_prefdialog.d.o ninja: build stopped: subcommand failed. ../source/gx/tilix/appwindow.d undefined reference to `_D6object__T8__equalsTxDFC2gx5tilix7session7SessionZvTxQBgZQBvFNaNbNiNfAxQByQfZb'
```